id: P638C4472
initial_creation_type: input
source_metadata:
  title: Machik Labdrön Series
  language: en
  description: 'Texts by and about Machik Labdrön (ma gcig lab sgron, 1031–1129 or
    1055–1149), the consort of Padampa Sangye and principal holder of the Chöd lineage:'
  volume:
    6bc4c132c9804b54a2642bc814f62a86:
      title: 'Cutting through the Four Demons in Absolute Space: A Praise of Machik
        Labdrön'
      parent: Praise
    2d0359aacd4448a693d7b305e40a8de1:
      title: Prayer to Machik Labdrön
      parent: Prayers
created_at: '2022-03-01T00:43:01.494663'
last_modified_at: '2022-03-01T00:43:01.494669'
